import { storage } from './storage';

/**
 * Test script to verify the customer creation system with the new ID handling
 * This tests the integration between storage.addCustomer and the returned customer_id
 */
export const testCustomerCreation = async () => {
  console.log('Testing Customer Creation System with ID Consistency...');
  
  try {
    // Create a test customer
    const testCustomer = {
      customer_id: '', // Will be generated by the system
      name: 'Test Customer',
      address: '123 Test Street',
      gstin: 'TESTGST123',
      dl_no: 'TESTDL123',
      state_code: '33',
      mobile: '9876543210'
    };
    
    console.log('1. Creating test customer...');
    console.log('   Input data:', testCustomer);
    
    // Add the customer
    const result = await storage.addCustomer(testCustomer);
    
    if (!result) {
      console.error('   Failed to create customer');
      return { success: false, error: 'Failed to create customer' };
    }
    
    console.log('2. Customer created successfully!');
    console.log('   Document ID:', result.documentId);
    console.log('   Customer ID:', result.customer_id);
    
    // Verify the customer ID format
    const isValidFormat = /^CUST\d{5}$/.test(result.customer_id);
    console.log(`   ID format validation: ${isValidFormat ? 'PASSED' : 'FAILED'}`);
    
    // Retrieve all customers to verify the customer was saved correctly
    console.log('3. Retrieving all customers to verify...');
    const customers = await storage.getCustomers();
    
    // Find our newly created customer
    const savedCustomer = customers.find(c => c.id === result.documentId);
    
    if (!savedCustomer) {
      console.error('   ERROR: Customer not found in database');
      return { success: false, error: 'Customer not found in database' };
    }
    
    console.log('   Found customer in database');
    console.log('   Saved customer ID:', savedCustomer.customer_id);
    console.log('   Saved customer name:', savedCustomer.name);
    
    // Verify the ID consistency
    const isIdConsistent = savedCustomer.customer_id === result.customer_id;
    console.log(`   ID consistency check: ${isIdConsistent ? 'PASSED' : 'FAILED'}`);
    
    // Summary
    console.log('\n=== TEST SUMMARY ===');
    console.log(`✓ Customer creation: ${result ? 'SUCCESS' : 'FAILED'}`);
    console.log(`✓ ID format validation: ${isValidFormat ? 'PASSED' : 'FAILED'}`);
    console.log(`✓ ID consistency check: ${isIdConsistent ? 'PASSED' : 'FAILED'}`);
    console.log('\nTest completed successfully!');
    
    return {
      success: true,
      documentId: result.documentId,
      customerId: result.customer_id,
      formatValid: isValidFormat,
      idConsistent: isIdConsistent
    };
    
  } catch (error) {
    console.error('Test failed with error:', error);
    return {
      success: false,
      error: error.message
    };
  }
};

/**
 * Test concurrent customer creation to verify no race conditions
 */
export const testConcurrentCustomerCreation = async () => {
  console.log('Testing Concurrent Customer Creation...');
  
  try {
    // Create 5 test customers with different names
    const testCustomers = Array.from({ length: 5 }, (_, i) => ({
      customer_id: '',
      name: `Test Customer ${i + 1}`,
      address: `${i + 1} Test Street`,
      gstin: `TESTGST${i + 1}`,
      dl_no: `TESTDL${i + 1}`,
      state_code: '33',
      mobile: `987654321${i}`
    }));
    
    console.log('1. Creating 5 customers concurrently...');
    
    // Create all customers concurrently
    const creationPromises = testCustomers.map(customer => storage.addCustomer(customer));
    const results = await Promise.all(creationPromises);
    
    console.log('2. All customers created!');
    
    // Extract all customer IDs
    const customerIds = results.map(r => r?.customer_id).filter(Boolean);
    const documentIds = results.map(r => r?.documentId).filter(Boolean);
    
    console.log('   Generated Customer IDs:', customerIds);
    console.log('   Document IDs:', documentIds);
    
    // Verify all IDs are unique
    const uniqueIds = [...new Set(customerIds)];
    const allUnique = uniqueIds.length === customerIds.length;
    console.log(`   All IDs unique: ${allUnique ? 'PASSED' : 'FAILED'}`);
    
    // Verify all IDs have correct format
    const allValidFormat = customerIds.every(id => /^CUST\d{5}$/.test(id || ''));
    console.log(`   All IDs valid format: ${allValidFormat ? 'PASSED' : 'FAILED'}`);
    
    // Verify sequential nature (they should be consecutive)
    const numericIds = customerIds.map(id => parseInt(id?.replace('CUST', '') || '0')).sort((a, b) => a - b);
    const isSequential = numericIds.every((id, index) => {
      if (index === 0) return true;
      return id === numericIds[index - 1] + 1;
    });
    console.log(`   IDs are sequential: ${isSequential ? 'PASSED' : 'FAILED'}`);
    
    // Summary
    console.log('\n=== CONCURRENT TEST SUMMARY ===');
    console.log(`✓ Created ${results.length} customers`);
    console.log(`✓ Uniqueness check: ${allUnique ? 'PASSED' : 'FAILED'}`);
    console.log(`✓ Format validation: ${allValidFormat ? 'PASSED' : 'FAILED'}`);
    console.log(`✓ Sequential check: ${isSequential ? 'PASSED' : 'FAILED'}`);
    console.log('\nConcurrent test completed successfully!');
    
    return {
      success: true,
      createdCount: results.length,
      allUnique,
      allValidFormat,
      isSequential,
      customerIds
    };
    
  } catch (error) {
    console.error('Concurrent test failed with error:', error);
    return {
      success: false,
      error: error.message
    };
  }
};