import { Platform, StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "@/utils/responsive";

export const contactsStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#000000",
	},
	header: {
		paddingHorizontal: scale(20),
		zIndex: 10,
		backgroundColor: "#000000",
		paddingTop: scale(10),
		paddingBottom: scale(10),
	},
	headerTop: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	headerTitle: {
		fontSize: moderateScale(32),
		fontWeight: "bold",
		color: "#FFFFFF",
		letterSpacing: -0.5,
	},
	settingsButton: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(24),
		justifyContent: "center",
		alignItems: "center",
	},
	searchContainer: {
		position: "relative",
		width: "100%",
		marginBottom: scale(10),
	},
	searchIcon: {
		position: "absolute",
		left: scale(20),
		top: scale(16),
		zIndex: 1,
	},
	searchInput: {
		width: "100%",
		height: verticalScale(56),
		backgroundColor: "#1C1C1E",
		borderRadius: scale(28),
		paddingLeft: scale(56),
		paddingRight: scale(16),
		fontSize: moderateScale(18),
		color: "#FFFFFF",
		fontWeight: "500",
	},
	contactList: {
		flex: 1,
		paddingHorizontal: scale(16),
		paddingTop: scale(5),
	},
	contactListContent: {
		paddingTop: scale(8),
		paddingBottom: verticalScale(120),
	},
	contactItem: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: "#1C1C1E",
		borderRadius: scale(16),
		paddingHorizontal: scale(16),
		paddingVertical: scale(16),
		marginBottom: scale(12),
		shadowColor: "#000000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	contactInfo: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
	},
	avatar: {
		width: scale(64),
		height: scale(64),
		borderRadius: scale(32),
		justifyContent: "center",
		alignItems: "center",
		marginRight: scale(20),
		borderWidth: 2,
		borderColor: "transparent",
	},
	avatarText: {
		fontSize: moderateScale(20),
		fontWeight: "bold",
	},
	contactDetails: {
		flex: 1,
		justifyContent: "center",
	},
	contactName: {
		fontSize: moderateScale(20),
		fontWeight: "bold",
		color: "#FFFFFF",
		marginBottom: scale(4),
	},
	contactPhone: {
		fontSize: moderateScale(18),
		fontWeight: "500",
		color: "#9CA3AF",
	},
	editButton: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(24),
		backgroundColor: "#000000",
		justifyContent: "center",
		alignItems: "center",
	},
	bottomSpacer: {
		height: verticalScale(32),
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: verticalScale(40),
	},
	loadingText: {
		color: "#FFFFFF",
		fontSize: moderateScale(16),
		marginTop: verticalScale(16),
		fontWeight: "500",
	},
	emptyContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: verticalScale(40),
	},
	emptyText: {
		color: "#9CA3AF",
		fontSize: moderateScale(16),
		fontWeight: "500",
	},
	fab: {
		position: "absolute",
		bottom: verticalScale(10),
		right: scale(20),
		width: scale(72),
		height: scale(72),
		borderRadius: scale(36),
		backgroundColor: "#13EC6A",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#13EC6A",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
		zIndex: 20,
	},
	fabSmall: {
		position: "absolute",
		bottom: verticalScale(30),
		right: scale(20),
		width: scale(56),
		height: scale(56),
		borderRadius: scale(28),
		backgroundColor: "#13EC6A",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#13EC6A",
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.25,
		shadowRadius: 6,
		elevation: 6,
		zIndex: 20,
	},
	bottomNav: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#000000",
		borderTopWidth: 1,
		borderTopColor: "#222222",
		paddingBottom: Platform.OS === "ios" ? 20 : 0,
	},
	navContainer: {
		flexDirection: "row",
		height: verticalScale(64),
		alignItems: "center",
		justifyContent: "space-around",
		paddingHorizontal: scale(8),
	},
	navItem: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: scale(8),
	},
	navLabel: {
		fontSize: moderateScale(12),
		fontWeight: "500",
		color: "#9CA3AF",
		marginTop: scale(4),
	},
	navLabelActive: {
		color: "#13EC6A",
		fontWeight: "bold",
	},

	// AvatarPreview styles
	avatarPreviewContainer: {
		alignItems: "center",
		marginBottom: verticalScale(32),
	},
	avatarPreview: {
		alignItems: "center",
		justifyContent: "center",
		marginBottom: verticalScale(16),
	},
	avatarPreviewText: {
		fontSize: moderateScale(42),
		fontWeight: "bold",
	},

	// ColorPicker styles
	colorPickerContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: scale(12),
		paddingHorizontal: scale(8),
	},
	colorOption: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(24),
		alignItems: "center",
		justifyContent: "center",
	},

	// DeleteContactButton styles
	deleteSection: {
		paddingTop: verticalScale(32),
		paddingBottom: verticalScale(16),
	},
	deleteButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(12),
		paddingVertical: scale(20),
		borderRadius: scale(25), // 50/2
		borderWidth: 2,
		borderColor: "rgba(239, 68, 68, 0.3)",
		backgroundColor: "rgba(239, 68, 68, 0.05)",
		marginBottom: scale(16),
	},
	deleteButtonText: {
		color: "#EF4444",
		fontSize: moderateScale(20),
		fontWeight: "bold",
		letterSpacing: 0.5,
	},
	deleteWarning: {
		textAlign: "center",
		color: "#6B7280",
		fontSize: moderateScale(14),
		fontWeight: "500",
	},
});
