import { Platform, StyleSheet } from "react-native";

export const contactsStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#000000",
	},
	header: {
		paddingHorizontal: 20,
		zIndex: 10,
		backgroundColor: "#000000",
		paddingTop: 10,
		paddingBottom: 10,
	},
	headerTop: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	headerTitle: {
		fontSize: 32,
		fontWeight: "bold",
		color: "#FFFFFF",
		letterSpacing: -0.5,
	},
	settingsButton: {
		width: 48,
		height: 48,
		borderRadius: 24,
		justifyContent: "center",
		alignItems: "center",
	},
	searchContainer: {
		position: "relative",
		width: "100%",
		marginBottom: 10,
	},
	searchIcon: {
		position: "absolute",
		left: 20,
		top: 16,
		zIndex: 1,
	},
	searchInput: {
		width: "100%",
		height: 56,
		backgroundColor: "#1C1C1E",
		borderRadius: 28,
		paddingLeft: 56,
		paddingRight: 16,
		fontSize: 18,
		color: "#FFFFFF",
		fontWeight: "500",
	},
	contactList: {
		flex: 1,
		paddingHorizontal: 16,
		paddingTop: 5,
	},
	contactListContent: {
		paddingTop: 8,
		paddingBottom: 120,
	},
	contactItem: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: "#1C1C1E",
		borderRadius: 16,
		paddingHorizontal: 16,
		paddingVertical: 16,
		marginBottom: 12,
		shadowColor: "#000000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	contactInfo: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
	},
	avatar: {
		width: 64,
		height: 64,
		borderRadius: 32,
		justifyContent: "center",
		alignItems: "center",
		marginRight: 20,
		borderWidth: 2,
		borderColor: "transparent",
	},
	avatarText: {
		fontSize: 20,
		fontWeight: "bold",
	},
	contactDetails: {
		flex: 1,
		justifyContent: "center",
	},
	contactName: {
		fontSize: 20,
		fontWeight: "bold",
		color: "#FFFFFF",
		marginBottom: 4,
	},
	contactPhone: {
		fontSize: 18,
		fontWeight: "500",
		color: "#9CA3AF",
	},
	editButton: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: "#000000",
		justifyContent: "center",
		alignItems: "center",
	},
	bottomSpacer: {
		height: 32,
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 40,
	},
	loadingText: {
		color: "#FFFFFF",
		fontSize: 16,
		marginTop: 16,
		fontWeight: "500",
	},
	emptyContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 40,
	},
	emptyText: {
		color: "#9CA3AF",
		fontSize: 16,
		fontWeight: "500",
	},
	fab: {
		position: "absolute",
		bottom: 10,
		right: 20,
		width: 72,
		height: 72,
		borderRadius: 36,
		backgroundColor: "#13EC6A",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#13EC6A",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
		zIndex: 20,
	},
	fabSmall: {
		position: "absolute",
		bottom: 30,
		right: 20,
		width: 56,
		height: 56,
		borderRadius: 28,
		backgroundColor: "#13EC6A",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#13EC6A",
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.25,
		shadowRadius: 6,
		elevation: 6,
		zIndex: 20,
	},
	bottomNav: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#000000",
		borderTopWidth: 1,
		borderTopColor: "#222222",
		paddingBottom: Platform.OS === "ios" ? 20 : 0,
	},
	navContainer: {
		flexDirection: "row",
		height: 64,
		alignItems: "center",
		justifyContent: "space-around",
		paddingHorizontal: 8,
	},
	navItem: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 8,
	},
	navLabel: {
		fontSize: 12,
		fontWeight: "500",
		color: "#9CA3AF",
		marginTop: 4,
	},
	navLabelActive: {
		color: "#13EC6A",
		fontWeight: "bold",
	},

	// AvatarPreview styles
	avatarPreviewContainer: {
		alignItems: "center",
		marginBottom: 32,
	},
	avatarPreview: {
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 16,
	},
	avatarPreviewText: {
		fontSize: 42,
		fontWeight: "bold",
	},

	// ColorPicker styles
	colorPickerContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 12,
		paddingHorizontal: 8,
	},
	colorOption: {
		width: 48,
		height: 48,
		borderRadius: 24,
		alignItems: "center",
		justifyContent: "center",
	},

	// DeleteContactButton styles
	deleteSection: {
		paddingTop: 32,
		paddingBottom: 16,
	},
	deleteButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 12,
		paddingVertical: 20,
		borderRadius: 50,
		borderWidth: 2,
		borderColor: "rgba(239, 68, 68, 0.3)",
		backgroundColor: "rgba(239, 68, 68, 0.05)",
		marginBottom: 16,
	},
	deleteButtonText: {
		color: "#EF4444",
		fontSize: 20,
		fontWeight: "bold",
		letterSpacing: 0.5,
	},
	deleteWarning: {
		textAlign: "center",
		color: "#6B7280",
		fontSize: 14,
		fontWeight: "500",
	},
});
