import { StyleSheet } from "react-native";

export const invoiceStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#000000",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		height: 64,
		backgroundColor: "rgba(0, 0, 0, 0.95)",
		borderBottomWidth: 1,
		borderBottomColor: "#374151",
	},
	backButton: {
		width: 48,
		height: 48,
		borderRadius: 24,
		alignItems: "center",
		justifyContent: "center",
	},
	headerTitle: {
		fontSize: 20,
		fontWeight: "800",
		flex: 1,
		textAlign: "center",
		color: "#ffffff",
	},
	cancelText: {
		fontSize: 16,
		fontWeight: "700",
		color: "#9db9a8",
	},
	scrollView: {
		flex: 1,
		paddingHorizontal: 16,
	},
	scrollContent: {
		paddingBottom: 100, // Add padding to account for fixed footer
	},
	section: {
		marginTop: 24,
		marginBottom: 12,
	},
	sectionTitle: {
		fontSize: 20,
		fontWeight: "700",
		color: "#ffffff",
		marginBottom: 12,
		paddingHorizontal: 4,
	},
	// Customer Selection Styles
	customerSection: {
		gap: 12,
	},
	customerSelect: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: "#121212",
		borderWidth: 2,
		borderColor: "#374151",
		borderRadius: 12,
		paddingHorizontal: 16,
		paddingVertical: 20,
	},
	customerSelectText: {
		fontSize: 18,
		fontWeight: "500",
		color: "#9ca3af",
	},
	createCustomerButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 12,
		borderWidth: 1,
		borderColor: "#374151",
		borderStyle: "dashed",
		borderRadius: 12,
		paddingVertical: 16,
		backgroundColor: "transparent",
	},
	createCustomerText: {
		fontSize: 16,
		fontWeight: "700",
		color: "#13ec6a",
	},
	// Product Styles
	productsSection: {
		gap: 16,
	},
	productCard: {
		backgroundColor: "#121212",
		borderRadius: 12,
		padding: 16,
		borderWidth: 1,
		borderColor: "#374151",
		gap: 16,
	},
	productHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	productInfo: {
		flex: 1,
	},
	productName: {
		fontSize: 18,
		fontWeight: "700",
		color: "#ffffff",
	},
	productDescription: {
		fontSize: 14,
		color: "#9ca3af",
		marginTop: 2,
	},
	removeButton: {
		padding: 4,
		marginLeft: -4,
	},
	productFooter: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: 4,
	},
	productPrice: {
		fontSize: 20,
		fontWeight: "700",
		color: "#ffffff",
	},
	stepper: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#000000",
		borderRadius: 8,
		padding: 4,
		gap: 16,
		borderWidth: 1,
		borderColor: "#374151",
	},
	stepperButton: {
		width: 40,
		height: 40,
		borderRadius: 6,
		backgroundColor: "#1E1E1E",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	stepperButtonPrimary: {
		width: 40,
		height: 40,
		borderRadius: 6,
		backgroundColor: "#13ec6a",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.3,
		shadowRadius: 2,
		elevation: 3,
	},
	stepperValue: {
		fontSize: 18,
		fontWeight: "700",
		color: "#ffffff",
		minWidth: 24,
		textAlign: "center",
	},
	addDiscountButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
		alignSelf: "flex-start",
		marginTop: 4,
	},
	addDiscountText: {
		fontSize: 14,
		fontWeight: "700",
		color: "#13ec6a",
		textDecorationLine: "underline",
	},
	discountInfo: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		fontSize: 14,
		color: "#9ca3af",
	},
	discountText: {
		color: "#13ec6a",
		fontWeight: "700",
	},
	editText: {
		textDecorationLine: "underline",
		fontSize: 12,
	},
	addProductButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		minHeight: 72,
		borderWidth: 2,
		borderColor: "rgba(19, 236, 106, 0.5)",
		borderStyle: "dashed",
		borderRadius: 12,
		backgroundColor: "rgba(19, 236, 106, 0.1)",
		paddingVertical: 16,
		marginTop: 8,
	},
	addProductIcon: {
		backgroundColor: "rgba(19, 236, 106, 0.2)",
		borderRadius: 24,
		padding: 4,
	},
	addProductText: {
		fontSize: 18,
		fontWeight: "700",
		color: "#13ec6a",
	},
	// Summary Styles
	summaryCard: {
		backgroundColor: "#121212",
		borderRadius: 12,
		padding: 20,
		borderWidth: 1,
		borderColor: "#374151",
		gap: 16,
	},
	summaryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	summaryLabel: {
		fontSize: 16,
		fontWeight: "500",
		color: "#9ca3af",
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	addDiscountBadge: {
		borderWidth: 1,
		borderColor: "rgba(19, 236, 106, 0.3)",
		paddingHorizontal: 8,
		paddingVertical: 2,
		borderRadius: 12,
	},
	addDiscountBadgeText: {
		fontSize: 12,
		fontWeight: "700",
		color: "#13ec6a",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	summaryValue: {
		fontSize: 16,
		fontWeight: "700",
		color: "#ffffff",
	},
	divider: {
		height: 1,
		backgroundColor: "#374151",
		marginVertical: 8,
	},
	totalRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-end",
	},
	totalLabel: {
		fontSize: 18,
		fontWeight: "700",
		color: "#ffffff",
		marginBottom: 4,
	},
	totalValue: {
		fontSize: 36,
		fontWeight: "800",
		color: "#13ec6a",
		letterSpacing: -1,
	},
	// Footer Styles
	footer: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#000000",
		borderTopWidth: 1,
		borderTopColor: "#374151",
		paddingHorizontal: 16,
		paddingVertical: 16,
		paddingBottom: 24,
	},
	previewButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		backgroundColor: "#13ec6a",
		height: 56,
		borderRadius: 12,
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 8,
		elevation: 8,
	},
	previewButtonText: {
		fontSize: 18,
		fontWeight: "800",
		color: "#000000",
	},
	// Discount Modal Styles
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.7)",
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 16,
	},
	modalContainer: {
		width: "100%",
		maxWidth: 360,
		backgroundColor: "#121212",
		borderRadius: 16,
		borderWidth: 1,
		borderColor: "rgba(19, 236, 106, 0.4)",
		padding: 24,
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 0.15,
		shadowRadius: 40,
		elevation: 40,
	},
	modalHeader: {
		alignItems: "center",
		marginBottom: 32,
	},
	modalTitle: {
		fontSize: 28,
		fontWeight: "800",
		color: "#ffffff",
		textAlign: "center",
		letterSpacing: -0.5,
	},
	// Toggle Switch Styles
	toggleContainer: {
		height: 56,
		width: "100%",
		backgroundColor: "#242424",
		borderRadius: 28,
		padding: 6,
		marginBottom: 40,
		borderWidth: 1,
		borderColor: "#333333",
		flexDirection: "row",
	},
	toggleOption: {
		flex: 1,
		height: "100%",
		borderRadius: 22,
		alignItems: "center",
		justifyContent: "center",
		flexDirection: "row",
		gap: 8,
		position: "relative",
	},
	toggleOptionActive: {
		backgroundColor: "#ffffff",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 3,
	},
	toggleText: {
		fontSize: 14,
		fontWeight: "700",
		color: "#777777",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	toggleTextActive: {
		color: "#000000",
	},
	// Input Styles
	inputContainer: {
		alignItems: "center",
		marginBottom: 32,
		width: "100%",
	},
	input: {
		width: "100%",
		backgroundColor: "transparent",
		fontSize: 64,
		fontWeight: "800",
		color: "#ffffff",
		textAlign: "center",
		padding: 0,
		borderWidth: 0,
		fontFamily: "monospace",
	},
	inputPlaceholder: {
		color: "#333333",
	},
	// Math Feedback Styles
	mathFeedback: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		marginTop: 16,
		marginBottom: 24, // Added margin to prevent overlap with buttons
	},
	mathFeedbackContainer: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 16,
		paddingVertical: 8,
		backgroundColor: "#1a2e23",
		borderRadius: 20,
		borderWidth: 1,
		borderColor: "#28392f",
	},
	mathFeedbackText: {
		fontSize: 14,
		fontWeight: "500",
		color: "#9db9a8",
	},
	mathFeedbackValue: {
		color: "#ffffff",
		fontWeight: "700",
	},
	// Action Buttons
	actionButtons: {
		flexDirection: "row",
		gap: 16,
		marginTop: "auto",
	},
	actionButton: {
		flex: 1,
		height: 56,
		borderRadius: 28,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
	},
	cancelButton: {
		backgroundColor: "#242424",
	},
	cancelButtonText: {
		fontSize: 16,
		fontWeight: "700",
		color: "#ffffff",
		letterSpacing: 0.5,
	},
	applyButton: {
		backgroundColor: "#13ec6a",
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 12,
		elevation: 8,
	},
	applyButtonText: {
		fontSize: 16,
		fontWeight: "700",
		color: "#102217",
		letterSpacing: 0.5,
	},
	// Invoice List Styles
	listContainer: {
		flex: 1,
		backgroundColor: "#000000",
	},
	listSearchContainer: {
		paddingHorizontal: 16,
		paddingBottom: 8,
	},
	listLightContainer: {
		flex: 1,
		backgroundColor: "#f6f8f7",
	},
	listLightSearchContainer: {
		paddingHorizontal: 16,
		paddingBottom: 8,
	},
	// Invoice List specific styles
	invoiceList: {
		flex: 1,
	},
	invoiceListContent: {
		paddingBottom: 120,
	},
});
