import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "@/utils/responsive";

export const invoiceStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#000000",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: scale(16),
		paddingVertical: scale(12),
		backgroundColor: "rgba(0, 0, 0, 0.95)",
		borderBottomWidth: 1,
		borderBottomColor: "#374151",
	},
	headerLeft: {
		flexDirection: "row",
		alignItems: "center",
	},
	headerActions: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(12),
	},
	headerActionButton: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(20),
		backgroundColor: "#1C1C1E",
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: "rgba(19, 236, 106, 0.3)",
	},
	backButton: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(24),
		alignItems: "center",
		justifyContent: "center",
	},
	scrollContainer: {
		flex: 1,
		backgroundColor: "#000000",
	},
	invoicePreviewScrollContent: {
		padding: scale(16),
		paddingBottom: verticalScale(100),
	},
	headerTitle: {
		fontSize: moderateScale(20),
		fontWeight: "800",
		flex: 1,
		textAlign: "center",
		color: "#ffffff",
	},
	cancelText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#9db9a8",
	},
	cancelButton: {
		paddingHorizontal: scale(8),
		height: scale(48),
		alignItems: "center",
		justifyContent: "center",
	},
	scrollView: {
		flex: 1,
		paddingHorizontal: scale(16),
	},
	scrollContent: {
		paddingBottom: verticalScale(100), // Add padding to account for fixed footer
	},
	section: {
		marginTop: verticalScale(24),
		marginBottom: verticalScale(12),
	},
	sectionTitle: {
		fontSize: moderateScale(20),
		fontWeight: "700",
		color: "#ffffff",
		marginBottom: verticalScale(12),
		paddingHorizontal: scale(4),
	},
	// Customer Selection Styles
	customerSection: {
		gap: scale(12),
	},
	customerSelect: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: "#121212",
		borderWidth: 2,
		borderColor: "#374151",
		borderRadius: scale(12),
		paddingHorizontal: scale(16),
		paddingVertical: scale(20),
	},
	customerSelectText: {
		fontSize: moderateScale(18),
		fontWeight: "500",
		color: "#9ca3af",
	},
	customerSelectedText: {
		fontSize: moderateScale(18),
		fontWeight: "500",
		color: "#ffffff",
	},
	createCustomerButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(12),
		borderWidth: 1,
		borderColor: "#374151",
		borderStyle: "dashed",
		borderRadius: scale(12),
		paddingVertical: scale(16),
		backgroundColor: "transparent",
	},
	createCustomerText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#13ec6a",
	},
	// Product Styles
	productsSection: {
		gap: scale(16),
	},
	productCard: {
		backgroundColor: "#121212",
		borderRadius: scale(12),
		padding: scale(16),
		borderWidth: 1,
		borderColor: "#374151",
		gap: scale(16),
	},
	productHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	productInfo: {
		flex: 1,
	},
	productName: {
		fontSize: moderateScale(18),
		fontWeight: "700",
		color: "#ffffff",
	},
	productDescription: {
		fontSize: moderateScale(14),
		color: "#9ca3af",
		marginTop: scale(2),
	},
	removeButton: {
		padding: scale(4),
		marginLeft: -scale(4),
	},
	productFooter: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: scale(4),
	},
	productPrice: {
		fontSize: moderateScale(20),
		fontWeight: "700",
		color: "#ffffff",
	},
	stepper: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#000000",
		borderRadius: scale(8),
		padding: scale(4),
		gap: scale(16),
		borderWidth: scale(1),
		borderColor: "#374151",
	},
	stepperButton: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(6),
		backgroundColor: "#1E1E1E",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	stepperButtonPrimary: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(6),
		backgroundColor: "#13ec6a",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.3,
		shadowRadius: 2,
		elevation: 3,
	},
	stepperValue: {
		fontSize: moderateScale(18),
		fontWeight: "700",
		color: "#ffffff",
		minWidth: scale(24),
		textAlign: "center",
	},
	addDiscountButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(4),
		alignSelf: "flex-start",
		marginTop: scale(4),
	},
	addDiscountText: {
		fontSize: moderateScale(14),
		fontWeight: "700",
		color: "#13ec6a",
		textDecorationLine: "underline",
	},
	discountInfo: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(8),
		fontSize: moderateScale(14),
		color: "#9ca3af",
	},
	discountText: {
		color: "#13ec6a",
		fontWeight: "700",
	},
	editText: {
		textDecorationLine: "underline",
		fontSize: moderateScale(12),
	},
	addProductButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(8),
		minHeight: verticalScale(72),
		borderWidth: scale(2),
		borderColor: "rgba(19, 236, 106, 0.5)",
		borderStyle: "dashed",
		borderRadius: scale(12),
		backgroundColor: "rgba(19, 236, 106, 0.1)",
		paddingVertical: scale(16),
		marginTop: scale(8),
	},
	addProductIcon: {
		backgroundColor: "rgba(19, 236, 106, 0.2)",
		borderRadius: scale(24),
		padding: scale(4),
	},
	addProductText: {
		fontSize: moderateScale(18),
		fontWeight: "700",
		color: "#13ec6a",
	},
	// Summary Styles
	summaryCard: {
		backgroundColor: "#121212",
		borderRadius: scale(12),
		padding: scale(20),
		borderWidth: 1,
		borderColor: "#374151",
		gap: scale(16),
	},
	summaryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	addDiscountBadge: {
		borderWidth: 1,
		borderColor: "rgba(19, 236, 106, 0.3)",
		paddingHorizontal: scale(8),
		paddingVertical: scale(2),
		borderRadius: scale(12),
	},
	addDiscountBadgeText: {
		fontSize: moderateScale(12),
		fontWeight: "700",
		color: "#13ec6a",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	summaryValue: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#ffffff",
	},
	divider: {
		height: scale(1),
		backgroundColor: "#374151",
		marginVertical: scale(8),
	},
	totalRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-end",
	},
	totalLabel: {
		fontSize: moderateScale(18),
		fontWeight: "700",
		color: "#ffffff",
		marginBottom: scale(4),
	},
	totalValue: {
		fontSize: moderateScale(36),
		fontWeight: "800",
		color: "#13ec6a",
		letterSpacing: -1,
	},
	// Footer Styles
	footer: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#000000",
		borderTopWidth: 1,
		borderTopColor: "#374151",
		paddingHorizontal: scale(16),
		paddingVertical: scale(16),
		paddingBottom: scale(24),
	},
	createButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(8),
		backgroundColor: "#13ec6a",
		height: verticalScale(56),
		borderRadius: scale(12),
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 8,
		elevation: 8,
	},
	createButtonText: {
		fontSize: moderateScale(18),
		fontWeight: "800",
		color: "#000000",
	},
	previewButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(8),
		backgroundColor: "#13ec6a",
		height: verticalScale(56),
		borderRadius: scale(12),
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 8,
		elevation: 8,
	},
	previewButtonText: {
		fontSize: moderateScale(18),
		fontWeight: "800",
		color: "#000000",
	},
	// Discount Modal Styles
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.7)",
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: scale(16),
	},
	modalContainer: {
		width: "100%",
		maxWidth: scale(400),
		alignSelf: "center",
		backgroundColor: "#121212",
		borderRadius: scale(16),
		borderWidth: 1,
		borderColor: "rgba(19, 236, 106, 0.4)",
		padding: scale(24),
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 0.15,
		shadowRadius: scale(40),
		elevation: 40,
	},
	modalHeader: {
		alignItems: "center",
		marginBottom: verticalScale(32),
	},
	modalTitle: {
		fontSize: moderateScale(28),
		fontWeight: "800",
		color: "#ffffff",
		textAlign: "center",
		letterSpacing: -0.5,
	},
	// Toggle Switch Styles
	toggleContainer: {
		height: verticalScale(56),
		width: "100%",
		backgroundColor: "#242424",
		borderRadius: scale(28),
		padding: scale(6),
		marginBottom: verticalScale(40),
		borderWidth: 1,
		borderColor: "#333333",
		flexDirection: "row",
	},
	toggleOption: {
		flex: 1,
		height: "100%",
		borderRadius: scale(22),
		alignItems: "center",
		justifyContent: "center",
		flexDirection: "row",
		gap: scale(8),
		position: "relative",
	},
	toggleOptionActive: {
		backgroundColor: "#ffffff",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: scale(2),
		elevation: 3,
	},
	toggleText: {
		fontSize: moderateScale(14),
		fontWeight: "700",
		color: "#777777",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	toggleTextActive: {
		color: "#000000",
	},
	// Input Styles
	inputContainer: {
		alignItems: "center",
		marginBottom: verticalScale(32),
		width: "100%",
	},
	input: {
		width: "100%",
		backgroundColor: "transparent",
		fontSize: moderateScale(64),
		fontWeight: "800",
		color: "#ffffff",
		textAlign: "center",
		padding: 0,
		borderWidth: 0,
		fontFamily: "monospace",
	},
	inputPlaceholder: {
		color: "#333333",
	},
	// Math Feedback Styles
	mathFeedback: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		marginTop: verticalScale(16),
		marginBottom: verticalScale(24), // Added margin to prevent overlap with buttons
	},
	mathFeedbackContainer: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(8),
		paddingHorizontal: scale(16),
		paddingVertical: scale(8),
		backgroundColor: "#1a2e23",
		borderRadius: scale(20),
		borderWidth: 1,
		borderColor: "#28392f",
	},
	mathFeedbackText: {
		fontSize: moderateScale(14),
		fontWeight: "500",
		color: "#9db9a8",
	},
	mathFeedbackValue: {
		color: "#ffffff",
		fontWeight: "700",
	},
	// Action Buttons
	actionButtons: {
		flexDirection: "row",
		gap: scale(16),
		marginTop: "auto",
	},
	actionButton: {
		flex: 1,
		height: verticalScale(56),
		borderRadius: scale(28),
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
	},
	cancelActionButton: {
		backgroundColor: "#242424",
	},
	cancelActionButtonText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#ffffff",
		letterSpacing: 0.5,
	},
	applyButton: {
		backgroundColor: "#13ec6a",
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: scale(12),
		elevation: 8,
	},
	applyButtonText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#102217",
		letterSpacing: 0.5,
	},
	// Invoice List Styles
	listContainer: {
		flex: 1,
		backgroundColor: "#000000",
	},
	listSearchContainer: {
		paddingHorizontal: scale(16),
		paddingBottom: scale(8),
	},
	listLightContainer: {
		flex: 1,
		backgroundColor: "#f6f8f7",
	},
	listLightSearchContainer: {
		paddingHorizontal: scale(16),
		paddingBottom: scale(8),
	},
	// Invoice List specific styles
	invoiceList: {
		flex: 1,
	},
	invoiceListContent: {
		paddingBottom: 120,
	},

	// Invoice preview styles
	deleteButton: {
		width: scale(48),
		height: scale(48),
		justifyContent: "center",
		alignItems: "flex-end",
	},
	previewContainer: {
		alignSelf: "center",
		backgroundColor: "#ffffff",
		borderRadius: scale(4),
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
		elevation: 5,
	},
	spacer: {
		height: verticalScale(96),
	},
	loadingOverlay: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: "rgba(0, 0, 0, 0.8)",
		justifyContent: "center",
		alignItems: "center",
		gap: scale(12),
		zIndex: 50,
	},
	loadingText: {
		fontSize: moderateScale(16),
		fontWeight: "600",
		color: "#ffffff",
	},
	errorContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		gap: scale(16),
	},
	errorText: {
		fontSize: moderateScale(18),
		fontWeight: "600",
		color: "#9ca3af",
	},
	placeholder: {
		width: scale(64),
	},

	// InvoiceActionBar styles (used by InvoiceActionBar component)
	actionBar: {
		position: "absolute",
		bottom: scale(16),
		left: scale(20),
		right: scale(20),
		flexDirection: "row",
		gap: scale(12),
	},
	paymentButton: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(4),
		height: verticalScale(64),
		backgroundColor: "#1C1C1E",
		borderRadius: scale(32),
		borderWidth: scale(1),
		borderColor: "rgba(19, 236, 106, 0.3)",
	},
	paymentButtonText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#ffffff",
	},
	saveButton: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(4),
		height: verticalScale(64),
		backgroundColor: "#1C1C1E",
		borderRadius: scale(32),
		borderWidth: scale(1),
		borderColor: "rgba(255, 255, 255, 0.1)",
	},
	saveButtonText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#ffffff",
	},
	shareButton: {
		flex: 1.2,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(4),
		height: verticalScale(64),
		backgroundColor: "#13ec6a",
		borderRadius: scale(32),
		shadowColor: "#13ec6a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.2,
		shadowRadius: 8,
		elevation: 8,
	},
	shareButtonText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#000000",
	},

	// InvoiceItem styles
	invoiceItem: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: scale(16),
		padding: scale(20),
		marginBottom: scale(16),
		borderRadius: scale(24),
		backgroundColor: "#161b18",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.05,
		shadowRadius: 2,
		elevation: 2,
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.05)",
	},
	checkboxWrapper: {
		marginLeft: -scale(8),
		padding: scale(4),
		opacity: 1,
	},
	checkbox: {
		width: scale(32),
		height: scale(32),
		borderRadius: scale(16),
		borderWidth: 2,
		borderColor: "rgba(255, 255, 255, 0.3)",
		backgroundColor: "transparent",
		justifyContent: "center",
		alignItems: "center",
	},
	checkboxChecked: {
		backgroundColor: "#13ec6a",
		borderColor: "#13ec6a",
	},
	checkIcon: {
		color: "#000000",
		fontSize: moderateScale(20),
	},
	invoiceContent: {
		flex: 1,
		gap: scale(4),
	},
	invoiceHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	customerName: {
		fontSize: moderateScale(20),
		fontWeight: "700",
		color: "#ffffff",
		flex: 1,
	},
	amount: {
		fontSize: moderateScale(20),
		fontWeight: "700",
	},
	amountPaid: {
		color: "#13ec6a",
	},
	amountPartial: {
		color: "#ffd700",
	},
	amountUnpaid: {
		color: "#ef4444",
	},
	invoiceDetails: {
		gap: scale(2),
	},
	detailText: {
		fontSize: moderateScale(14),
		color: "#9ca3af",
		fontWeight: "500",
	},
	statusBadge: {
		alignSelf: "flex-start",
		marginTop: scale(8),
		flexDirection: "row",
		alignItems: "center",
		gap: scale(6),
		paddingHorizontal: scale(12),
		paddingVertical: scale(4),
		borderRadius: scale(12),
	},
	statusBadgePaid: {
		backgroundColor: "rgba(19, 236, 106, 0.2)",
	},
	statusBadgePartial: {
		backgroundColor: "rgba(255, 215, 0, 0.2)",
	},
	statusBadgeUnpaid: {
		backgroundColor: "rgba(239, 68, 68, 0.2)",
	},
	statusText: {
		fontSize: moderateScale(12),
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	statusTextPaid: {
		color: "#13ec6a",
	},
	statusTextPartial: {
		color: "#ffd700",
	},
	statusTextUnpaid: {
		color: "#ef4444",
	},

	// PageIndicator styles
	pageIndicator: {
		marginTop: scale(24),
		alignSelf: "center",
		backgroundColor: "#1C1C1E",
		borderRadius: 9999,
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.1)",
		paddingHorizontal: scale(12),
		paddingVertical: scale(4),
	},
	pageIndicatorText: {
		fontSize: moderateScale(12),
		fontWeight: "600",
		color: "#9CA3AF",
	},

	// PaymentModal specific styles
	subtitle: {
		fontSize: moderateScale(16),
		color: "#9CA3AF",
		marginTop: scale(4),
		fontWeight: "500",
	},
	currencyPrefix: {
		fontSize: moderateScale(64),
		fontWeight: "800",
		color: "#13ec6a",
		marginRight: scale(4),
	},
	clearButton: {
		position: "absolute",
		right: 0,
		top: "50%",
		marginTop: -scale(12),
		backgroundColor: "#2a2a2a",
		borderRadius: scale(12),
		padding: scale(2),
	},
	quickActions: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: verticalScale(32),
		paddingHorizontal: scale(8),
	},
	quickChip: {
		backgroundColor: "rgba(19, 236, 106, 0.1)",
		paddingHorizontal: scale(16),
		paddingVertical: scale(8),
		borderRadius: scale(20),
		borderWidth: 1,
		borderColor: "rgba(19, 236, 106, 0.3)",
	},
	quickChipText: {
		color: "#13ec6a",
		fontWeight: "700",
		fontSize: moderateScale(14),
	},
	balanceContainer: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(8),
	},
	balanceLabel: {
		color: "#9CA3AF",
		fontSize: moderateScale(14),
	},
	balanceValue: {
		fontSize: moderateScale(16),
		fontWeight: "700",
	},

	// ZoomHint styles
	zoomHint: {
		position: "absolute",
		top: scale(16),
		left: scale(16),
		right: scale(16),
		zIndex: 10,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: scale(8),
		alignSelf: "center",
		backgroundColor: "rgba(28, 28, 30, 0.95)",
		borderRadius: 9999,
		paddingHorizontal: scale(16),
		paddingVertical: scale(8),
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 5,
	},
	zoomHintText: {
		fontSize: moderateScale(14),
		fontWeight: "500",
		color: "#9CA3AF",
	},

	// ContactPickerModal styles
	contactItem: {
		borderBottomWidth: 1,
		borderBottomColor: "rgba(255, 255, 255, 0.1)",
	},
	contactContent: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: scale(16),
		paddingHorizontal: scale(8),
		marginHorizontal: -scale(8),
		borderRadius: scale(12),
	},
	contactContentPressed: {
		backgroundColor: "rgba(255, 255, 255, 0.05)",
	},
	selectButton: {
		height: verticalScale(44),
		minWidth: scale(96),
		borderRadius: 9999,
		borderWidth: 2,
		borderColor: "#13ec6a",
		backgroundColor: "transparent",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "rgba(19, 236, 106, 0.1)",
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 1,
		shadowRadius: 10,
		elevation: 3,
	},
	selectButtonSelected: {
		backgroundColor: "#13ec6a",
		shadowColor: "rgba(19, 236, 106, 0.4)",
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 1,
		shadowRadius: 15,
		elevation: 5,
	},
	selectButtonContent: {
		fontSize: moderateScale(14),
		fontWeight: "700",
		color: "#13ec6a",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	selectedButtonContent: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(4),
	},
	selectedButtonText: {
		fontSize: moderateScale(14),
		fontWeight: "700",
		color: "#000000",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	contactListContent: {
		paddingHorizontal: scale(20),
		paddingBottom: scale(120),
	},

	// ProductPickerModal styles
	productItem: {
		borderBottomWidth: 1,
		borderBottomColor: "rgba(255, 255, 255, 0.1)",
	},
	productContent: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: scale(16),
		paddingHorizontal: scale(8),
		marginHorizontal: -scale(8),
		borderRadius: scale(12),
	},
	productContentPressed: {
		backgroundColor: "rgba(255, 255, 255, 0.05)",
	},
	productRightSection: {
		flexDirection: "column",
		alignItems: "flex-end",
		gap: scale(8),
	},
	addButton: {
		height: verticalScale(44),
		minWidth: scale(96),
		borderRadius: 9999,
		borderWidth: 2,
		borderColor: "#13ec6a",
		backgroundColor: "transparent",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "rgba(19, 236, 106, 0.1)",
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 1,
		shadowRadius: 10,
		elevation: 3,
	},
	addButtonSelected: {
		backgroundColor: "#13ec6a",
		shadowColor: "rgba(19, 236, 106, 0.4)",
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 1,
		shadowRadius: 15,
		elevation: 5,
	},
	addButtonContent: {
		fontSize: moderateScale(14),
		fontWeight: "700",
		color: "#13ec6a",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	addedButtonContent: {
		flexDirection: "row",
		alignItems: "center",
		gap: scale(4),
	},
	addedButtonText: {
		fontSize: moderateScale(14),
		fontWeight: "700",
		color: "#000000",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	productListContent: {
		paddingHorizontal: scale(20),
		paddingBottom: scale(120),
	},

	// ContactPickerModal styles (additional missing styles)
	contactInfo: {
		flex: 1,
	},
	contactName: {
		fontSize: moderateScale(18),
		fontWeight: "600",
		color: "#ffffff",
		lineHeight: moderateScale(24),
	},

	// InvoicePreviewCard styles
	previewCardContainer: {
		width: "100%",
		maxWidth: scale(400),
		alignSelf: "center",
		backgroundColor: "#ffffff",
	},
	previewCardPaper: {
		padding: scale(32),
		backgroundColor: "#ffffff",
	},
	previewCardHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		paddingBottom: scale(16),
		borderBottomWidth: 2,
		borderBottomColor: "#1e293b",
		marginBottom: verticalScale(24),
	},
	previewCardHeaderLeft: {
		flexDirection: "column",
	},
	invoiceTitle: {
		fontSize: moderateScale(28),
		fontWeight: "900",
		textTransform: "uppercase",
		letterSpacing: -0.5,
		color: "#1e293b",
	},
	invoiceNumber: {
		fontSize: moderateScale(16),
		fontWeight: "600",
		color: "#64748b",
		marginTop: scale(4),
	},
	logo: {
		width: scale(48),
		height: scale(48),
		backgroundColor: "#1e293b",
		borderRadius: scale(8),
		alignItems: "center",
		justifyContent: "center",
	},
	logoText: {
		fontSize: moderateScale(24),
		fontWeight: "700",
		color: "#ffffff",
	},
	billToSection: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: scale(32),
	},
	billToLeft: {
		flex: 1,
	},
	billToRight: {
		alignItems: "flex-end",
	},
	sectionLabel: {
		fontSize: moderateScale(12),
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.5,
		color: "#94a3b8",
		marginBottom: scale(4),
	},
	previewCardCustomerName: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#1e293b",
		lineHeight: moderateScale(20),
	},
	customerPhone: {
		fontSize: moderateScale(14),
		color: "#64748b",
		marginTop: scale(4),
	},
	customerDetail: {
		fontSize: moderateScale(13),
		color: "#64748b",
		marginTop: scale(2),
		lineHeight: moderateScale(18),
	},
	dateText: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#1e293b",
	},
	mt2: {
		marginTop: scale(12),
	},
	totalAmount: {
		fontSize: moderateScale(20),
		fontWeight: "900",
		color: "#1e293b",
	},
	itemsSection: {
		flex: 1,
		marginBottom: scale(24),
	},
	tableHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingBottom: scale(12),
		borderBottomWidth: 1,
		borderBottomColor: "#e2e8f0",
	},
	tableHeaderLabel: {
		fontSize: moderateScale(12),
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.5,
		color: "#94a3b8",
	},
	tableRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		paddingVertical: scale(16),
	},
	borderBottom: {
		borderBottomWidth: 1,
		borderBottomColor: "#f1f5f9",
	},
	itemDetails: {
		flex: 1,
	},
	itemName: {
		fontSize: moderateScale(16),
		fontWeight: "600",
		color: "#1e293b",
		marginBottom: scale(4),
	},
	itemMeta: {
		fontSize: moderateScale(13),
		color: "#64748b",
		marginBottom: scale(2),
	},
	discount: {
		marginTop: scale(4),
	},
	previewCardDiscountText: {
		fontSize: moderateScale(12),
		color: "#13ec6a",
		fontWeight: "600",
	},
	itemAmount: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#1e293b",
	},
	textRight: {
		textAlign: "right",
	},
	previewCardSummarySection: {
		borderTopWidth: 2,
		borderTopColor: "#1e293b",
		paddingTop: scale(20),
	},
	previewCardSummaryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: scale(12),
	},
	previewCardSummaryLabel: {
		fontSize: moderateScale(14),
		fontWeight: "600",
		color: "#64748b",
	},
	previewCardSummaryValue: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#1e293b",
	},
	discountValue: {
		color: "#ef4444",
	},
	previewCardTotalRow: {
		marginTop: scale(8),
		marginBottom: 0,
	},
	previewCardTotalLabel: {
		fontSize: moderateScale(16),
		fontWeight: "700",
		color: "#1e293b",
	},
	previewCardTotalValue: {
		fontSize: moderateScale(32),
		fontWeight: "900",
		color: "#1e293b",
		letterSpacing: -1,
	},
	previewCardFooter: {
		marginTop: scale(24),
		paddingTop: scale(24),
		borderTopWidth: 1,
		borderTopColor: "#e2e8f0",
		alignItems: "center",
	},
	previewCardFooterText: {
		fontSize: moderateScale(14),
		fontWeight: "600",
		color: "#1e293b",
	},
	previewCardFooterSubtext: {
		fontSize: moderateScale(12),
		color: "#94a3b8",
		marginTop: scale(4),
	},

	// Invoice detail page styles
	invoiceDetailPageScrollView: {
		flex: 1,
	},
	invoiceDetailPageScrollContent: {
		paddingTop: scale(16),
		paddingBottom: scale(200),
		paddingHorizontal: scale(16),
	},

	// Additional styles needed by components
	summaryLabel: {
		fontSize: moderateScale(14),
		fontWeight: "600",
		color: "#64748b",
	},
	paper: {
		padding: scale(32),
		backgroundColor: "#ffffff",
	},
	summarySection: {
		borderTopWidth: 2,
		borderTopColor: "#1e293b",
		paddingTop: scale(20),
	},
});
